version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_queue
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    container_name: django_app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    container_name: celery_worker
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
